# -*- coding: utf-8 -*-
"""Deep Learning ahmed khalil.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SpnamuZYKAEBssFAxp3VVNS2VdJDXA4N
"""

import tensorflow as tf
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.optimizers import Adam


base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(224, 224, 3))

for layer in base_model.layers:
    layer.trainable = False

x = base_model.output

x = GlobalAveragePooling2D()(x)

x = Dense(256, activation='relu')(x)

x = Dropout(0.5)(x)

predictions = Dense(1, activation='sigmoid')(x)

model = Model(inputs=base_model.input, outputs=predictions)

model.compile(optimizer=Adam(learning_rate=0.001),
              loss='binary_crossentropy',
              metrics=['accuracy'])

print("تم بناء نموذج ResNet50 بنجاح لمرحلة استخراج الميزات (Feature Extraction)!")
model.summary()

# ---------------------------------------------------------

for layer in base_model.layers[-10:]:
    layer.trainable = True

model.compile(optimizer=Adam(learning_rate=1e-5),
              loss='binary_crossentropy',
              metrics=['accuracy'])

print("النموذج الآن جاهز لمرحلة الضبط الدقيق (Fine-Tuning)!")

